export enum Domain {
	COMPUTER_SCIENCE = 'COMPUTER_SCIENCE',
	PSYCHOLOGY = 'PSYCHOLOGY',
	MEDICINE = 'MEDICINE',
	PHARMACY = 'PHARMACY',
	ECONOMICS = 'ECONOMICS',
	BIOLOGY = 'BIOLOGY',
	HISTORY = 'HISTORY',
	OTHERS = 'OTHERS'
}
